version: '3'
services:
  test:
    build:
      context: '.'
      dockerfile: Dockerfile.test
    container_name: front_test
    image: front_test
    ports:
      - 5000:5000
  locale:
    build:
      context: '.'
      dockerfile: Dockerfile.local
    container_name: front_locale
    image: front_locale
    ports:
      - 5001:5001
